
# Site settings
title:        The OpenSextant Project
tagline:      A geospatial stuff project
description:  geospatial capabilities like geotagging nd entity extraction
logo: "sextant.png"

# About/contact
author:  The OpenSextant Team

baseurl:      ""
url: "http://opensextant.github.io"

#Build settings
markdown: kramdown
kramdown:
   auto_ids: true
