
# Site settings
title:        The OpenSextant Project
tagline:      A geospatial stuff project
description:  A GitHub project for geotagging and other geospatial capabilities
logo: "https://avatars.githubusercontent.com/u/4237411"

# About/contact
author:  The OpenSextant Team

baseurl:      ""
url: "http://opensextant.github.io"

#Build settings
markdown: kramdown
kramdown:
   auto_ids: true

gems:
  - jekyll-seo-tag