
# Site settings
title:        The OpenSextant Project
tagline:      Smart geospatial extraction for any data.
description:  geospatial capabilities like geotagging nd entity extraction
logo: "sextant.png"

# About/contact
author:  The OpenSextant Team

baseurl:      ""
url: "http://opensextant.github.io"

theme: jekyll-theme-modernist

#Build settings
markdown: kramdown
kramdown:
   auto_ids: true
